name: wifi_info_plugin
description: Wifi info wrapper android plugin
version: 1.0.1
author: Kirk-Patrick Brown <vtechjm@gmail.com>
homepage: https://github.com/VTechJm

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.vtechjm.wifi_info_plugin
    pluginClass: WifiInfoPlugin


